import React, { useState } from 'react';
import { supabase } from '../../lib/supabase';

const PostWork = () => {
  const [formData, setFormData] = useState({
    work_name: '',
    instruction: '',
    total_slots: '',
    number_of_days: '',
    location: '',
    date_of_work: '',
    reporting_time: '',
    completion_time: '',
    payment_amount: '',
    payment_date: ''
  });
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validation
    if (formData.reporting_time && formData.completion_time) {
      if (formData.completion_time <= formData.reporting_time) {
        alert("Oops! The Completion Time must be after the Reporting Time.");
        return;
      }
    }

    if (!supabase) {
      alert("Supabase is not connected! Please provide your API keys in the .env file.");
      return;
    }

    setLoading(true);
    
    const { data, error } = await supabase
      .from('works')
      .insert([
        {
          client_id: localStorage.getItem('dothozhil_username') || 'guest_client_123',
          work_name: formData.work_name,
          instruction: formData.instruction,
          total_slots: parseInt(formData.total_slots),
          available_slots: parseInt(formData.total_slots), // Initially available = total
          number_of_days: parseInt(formData.number_of_days),
          location: formData.location,
          date_of_work: formData.date_of_work,
          reporting_time: formData.reporting_time,
          completion_time: formData.completion_time,
          payment_amount: parseInt(formData.payment_amount),
          payment_date: formData.payment_date,
          status: 'Active'
        }
      ]);

    setLoading(false);

    if (error) {
      alert("Error posting work: " + error.message);
      console.error(error);
    } else {
      alert("Work broadcasted successfully!");
      // Reset form
      setFormData({
        work_name: '', instruction: '', total_slots: '', number_of_days: '', location: '',
        date_of_work: '', reporting_time: '', completion_time: '',
        payment_amount: '', payment_date: ''
      });
    }
  };

  return (
    <div className="page-content">
      <div style={{ maxWidth: '800px', margin: '0 auto' }}>
        <h1 style={{ fontSize: '1.8rem', fontWeight: '700', marginBottom: '0.5rem' }}>Post A Work</h1>
        <p style={{ color: 'var(--text-muted)', marginBottom: '2rem' }}>Fill out the details to broadcast your work requirement to workers.</p>

        <div className="card">
          {!supabase && (
             <div style={{ backgroundColor: '#fef2f2', color: '#b91c1c', padding: '1rem', borderRadius: '0.5rem', marginBottom: '1.5rem', fontWeight: '500' }}>
               Backend disconnected. Please add your Supabase URL and Key to the .env file.
             </div>
          )}

          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <div>
              <label className="label">Work ID (Auto-generated)</label>
              <input type="text" className="input-field" value="Will be generated by DB" disabled style={{ backgroundColor: '#f9fafb' }} />
            </div>
            
            <div>
              <label className="label">Work Name *</label>
              <input type="text" name="work_name" value={formData.work_name} onChange={handleChange} className="input-field" placeholder="e.g. Catering Staff for Wedding" required />
            </div>

            <div>
              <label className="label">Work Instruction *</label>
              <textarea name="instruction" value={formData.instruction} onChange={handleChange} className="input-field" placeholder="Detailed instructions for the workers..." rows={4} required></textarea>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
              <div>
                <label className="label">Total Number of Slots *</label>
                <input type="number" name="total_slots" value={formData.total_slots} onChange={handleChange} className="input-field" placeholder="e.g. 5" min="1" required />
              </div>
              <div>
                <label className="label">Number of Days *</label>
                <input type="number" name="number_of_days" value={formData.number_of_days} onChange={handleChange} className="input-field" placeholder="e.g. 1" min="1" required />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
              <div>
                <label className="label">Location *</label>
                <input type="text" name="location" value={formData.location} onChange={handleChange} className="input-field" placeholder="e.g. Ernakulam, Kerala" required />
              </div>
              <div>
                <label className="label">Date(s) of Work *</label>
                <input type="date" name="date_of_work" min={new Date().toISOString().split('T')[0]} value={formData.date_of_work} onChange={handleChange} className="input-field" required />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
              <div>
                <label className="label">Reporting Time *</label>
                <input type="time" name="reporting_time" value={formData.reporting_time} onChange={handleChange} className="input-field" required />
              </div>
              <div>
                <label className="label">Completion Time *</label>
                <input type="time" name="completion_time" value={formData.completion_time} onChange={handleChange} className="input-field" required />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
              <div>
                <label className="label">Payment Amount (₹) *</label>
                <input type="number" name="payment_amount" value={formData.payment_amount} onChange={handleChange} className="input-field" placeholder="e.g. 800" min="0" required />
              </div>
              <div>
                <label className="label">Payment will Credit on *</label>
                <input type="date" name="payment_date" min={formData.date_of_work || new Date().toISOString().split('T')[0]} value={formData.payment_date} onChange={handleChange} className="input-field" required />
              </div>
            </div>

            <div style={{ marginTop: '1rem' }}>
              <button type="submit" className="btn-primary" style={{ width: '100%' }} disabled={loading}>
                {loading ? 'Broadcasting...' : 'Broadcast Work'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default PostWork;
